name: Docker Image CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag rdnuansa/space-invader-web:${{  github.ref_name }}
    

  push:
    runs-on: self-hosted
    steps:
      - name: Push Docker image
        run: docker push rdnuansa/space-invader-web:${{  github.ref_name }}
  
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy container
        run: docker run -d -p 80:80 --name space-invader rdnuansa/space-invader-web:${{  github.ref_name }}
